### ISSUE TITLE
Issue about PatchMix strategy

### ISSUE THREAD

**Issue by viviGeng** [corwinliu9669/Learning-a-Few-shot-Embedding-Model-with-Contrastive-Learning#3]
Hi. 

Could you explain how you construct the positive pair and negative pair when PatchMix is applied?
What is the label of the replaced patch?

Looking forward to your reply.

**Comment by corwinliu9669** [comment]
Please refer to Method section of https://www.aaai.org/AAAI21Papers/AAAI-2249.LiuC.pdf. I think it has been explained clearly in this paper. And PatchMix implementation is here(https://github.com/corwinliu9669/Learning-a-Few-shot-Embedding-Model-with-Contrastive-Learning/blob/218fcb153b7bd43c4bff7d889c88123e5ec451c9/utils.py#L53).

**Comment by viviGeng** [comment]
> Please refer to Method section of https://www.aaai.org/AAAI21Papers/AAAI-2249.LiuC.pdf. I think it has been explained clearly in this paper. And PatchMix implementation is here(
> 
> https://github.com/corwinliu9669/Learning-a-Few-shot-Embedding-Model-with-Contrastive-Learning/blob/218fcb153b7bd43c4bff7d889c88123e5ec451c9/utils.py#L53
> 
> ).

My understanding is that each split patch can only be assign to one label either the replaced tag or the original tag.
The purpose of Patch Mix is to increase the probability of constructing various images as constructive pairs. However, the probability should be the same as the one without PatchMix strategy if the model is trained completely.

**Comment by corwinliu9669** [comment]
> > Please refer to Method section of https://www.aaai.org/AAAI21Papers/AAAI-2249.LiuC.pdf. I think it has been explained clearly in this paper. And PatchMix implementation is here(
> > https://github.com/corwinliu9669/Learning-a-Few-shot-Embedding-Model-with-Contrastive-Learning/blob/218fcb153b7bd43c4bff7d889c88123e5ec451c9/utils.py#L53
> > 
> > ).
> 
> My understanding is that each split patch can only be assign to one label either the replaced tag or the original tag. The purpose of Patch Mix is to increase the probability of constructing various images as constructive pairs. However, the probability should be the same as the one without PatchMix strategy if the model is trained completely.

"My understanding is that each split patch can only be assign to one label either the replaced tag or the original tag.", it is correct.
 "The purpose of Patch Mix is to increase the probability of constructing various images as constructive pairs. However, the probability should be the same as the one without PatchMix strategy if the model is trained completely.", I don't understand your concern. I guess you mean the switch will not alter the distribution of patches in all. If each patch is trained in isolation, you are right. However, if you have ever read the code and the paper, you can find that the images after PatchMix are fed into the network as whole instead of patch by patch. And it is the difference. Again, I think these are explained in the paper and the code.
