### ISSUE TITLE
Visualization of heatmaps

### ISSUE THREAD

**Issue by LoveMiki** [corwinliu9669/Learning-a-Few-shot-Embedding-Model-with-Contrastive-Learning#4]
Hi,
I am very interested in the heatmap visualizations you had shown in Figure 2. 
Can you share the implementation code?

Thank you in advance.

**Comment by corwinliu9669** [comment]
Please refer to the implementation detail in the caption.

**Comment by LoveMiki** [comment]
> Please refer to the implementation detail in the caption.

So, you didn't use CAM to generate but directly used inner product and visualize in form of heatmap?
However, previous work CAN (which is very similar to your work) used CAM to visualize the heatmap, and it seems that it may not be able to generate such visualization based on your description in Fig. 2 .

**Comment by corwinliu9669** [comment]
(So, you didn't use CAM to generate but directly used inner product and visualize in form of heatmap?) For this issue, I do not know how to get CAM without a classifier on Novel data. If you know how to get that one, please tell me! Thank you in advance.(it seems that it may not be able to generate such visualization based on your description in Fig. 2 .) Well, if you implement it and find it hard to reproduce, then show me your reproduce code. Otherwise please do not waste my time.
